name: Static Analysis

on:
  push:
    paths-ignore:
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'docs/**'

jobs:
  cs:
    runs-on: ubuntu-latest

    name: Code Style

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        tools: composer:v2
        coverage: none

    - name: Install Dependencies
      run: composer update --no-interaction --no-progress --ansi

    - name: Run PHP-CS-Fixer
      run: vendor/bin/pint --test

  phpstan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dependency-version: [prefer-lowest, prefer-stable]

    name: PHPStan ${{ matrix.dependency-version }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        tools: composer:v2
        coverage: none

    - name: Install Dependencies
      run: composer update --prefer-stable --no-interaction --no-progress --ansi

    - name: Run PHPStan
      run: vendor/bin/phpstan analyse --memory-limit=-1 --debug --no-progress --ansi
